services:
  spark:
    build: .
    container_name: spark_container
    volumes:
      - ./data:/app/data
      - ./src:/app/src/
      - ./notebooks:/app/notebooks
      - ./results:/app/results
    ports:
      - "4040:4040"
      - "8888:8888"
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
    tty: true
    restart: unless-stopped
